version: '2'
services:
  nginx:
    image: nginx
    ports:
       - "8080:80"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
       - jira:jira
    depends_on:
      - jira

  jira:
     image: cptactionhank/atlassian-jira-software:7.0.9
     ports:
      - "2990:8080"
     environment:
       X_PROXY_NAME: nginx.jira
       X_PROXY_PORT: 8080
       X_PROXY_SCHEME: http