version: '2'
services:
  nginx:
    image: blacklabelops/nginx
    ports:
       - "8080:8080"
    links:
       - jira:jira
    depends_on:
      - jira
    environment:
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://jira:8080
      SERVER_NAME: jira-behind-nginx.com

  jira:
     image: cptactionhank/atlassian-jira-software:7.0.9
     ports:
      - "2990:8080"
     environment:
       X_PROXY_NAME: jira-behind-nginx.com
       X_PROXY_PORT: 8080
       X_PROXY_SCHEME: http
