version: '2'
services:
  jira:
    image: cptactionhank/atlassian-jira-service-desk
    depends_on:
      - db
    ports:
      - "8080:8080"
  confluence:
    image: cptactionhank/atlassian-confluence:5.9.9
    depends_on:
      - db
      - jira
    ports:
      - "8090:8090"
  db:
    image: postgres
    ports: 
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: password