version: '2'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.1.4
    depends_on:
      - db
    ports:
      - "8714:8080"
      - "5714:5005"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  confluence:
    image: cptactionhank/atlassian-confluence:5.9.9
    depends_on:
      - db
      - jira
    ports:
      - "8599:8090"
  db:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: password