version: '2'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.1.4
    depends_on:
      - db
    ports:
      - "5080:8080"
      - "5085:5005"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  confluence:
    image: cptactionhank/atlassian-confluence:6.0.7
    depends_on:
      - db
      - jira
    ports:
      - "5090:8090"
      - "5095:5005"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  db:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: password