version: '2'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.6.0
    depends_on:
      - db
    ports:
      - "6080:8080"
      - "6085:5005"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - ./jira-home:/var/atlassian/jira
  confluence:
    image: cptactionhank/atlassian-confluence:6.5.0
    depends_on:
      - mysql
    ports:
      - "6090:8090"
      - "6095:5005"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - ./confluence-home:/var/atlassian/confluence
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql.conf.d:/etc/mysql/conf.d
